backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow

collections:
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Config"
        file: "config.json"
        description: "General site settings"
        fields:
          - label: "URL"
            name: "base_url"
            widget: "string"
            hint: "Do not enter the trailing slash of the URL"
          - label: "Site title"
            name: "site_title"
            widget: "string"
          - label: "Site description"
            name: "site_description"
            widget: "string"
          - label: "Site keywords"
            name: "site_keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: "string"
          - label: "Copyright"
            name: "copyright"
            widget: "string"
            hint: "Copyright notice for the site"

  - name: "meta"
    label: "Meta"
    delete: false
    editor:
      preview: false
    files:
      - name: "authors"
        label: "Authors"
        file: "meta/authors.yml"
        description: "Author descriptions"
        fields:
          - name: authors
            label: Authors
            label_singular: "Author"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the author"
              - label: "Name"
                name: "name"
                widget: "string"
                hint: "First and Last"
              - label: "Introduction"
                name: "introduction"
                widget: "text"
      - name: "tags"
        label: "Tags"
        file: "meta/tags.yml"
        description: "List of tags"
        fields:
          - name: tags
            label: Tags
            label_singular: "Tag"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the tag"
              - label: "Display Name"
                name: "name"
                widget: "string"
                hint: "Tag name for displaying on the site"

  - name: "pages"
    label: "Pages"
    delete: false
    files:
      - name: "home"
        label: "Home Page"
        file: "content/pages/home.mdx"
        fields:
          - label: "Hero Image"
            name: "heroImage"
            widget: "image"
          - label: "Hero Title"
            name: "heroTitle"
            widget: "markdown"
          - label: "Hero Text"
            name: "heroText"
            widget: "markdown"
          - label: "Hero Button Label"
            name: "heroButtonLabel"
            widget: "string"
          - label: "Large Quote Text"
            name: "largeQuote"
            widget: "markdown"
          - label: "Section Blocks"
            name: "sections"
            widget: "list"
            summary: "{{fields.title}}"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Title", name: "title", widget: "markdown" }
              - { label: "Text", name: "text", widget: "markdown" }
          - label: "Contact Section"
            name: "contact"
            widget: "object"
            summary: "{{fields.title}}"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Text", name: "text", widget: "string" }
              - { label: "Button Label", name: "buttonLabel", widget: "string" }

      - name: "team"
        label: "Team Page"
        file: "content/pages/team.mdx"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - label: "Team Members"
            name: "teamMembers"
            widget: "list"
            summary: "{{fields.name}}"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Bio", name: "bio", widget: "markdown" }
      
      - name: "contact"
        label: "Contact Page"
        file: "content/pages/contact.mdx"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Address", name: "address", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }

  - name: "news"
    label: "News"
    folder: "content/news/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", dateFormat: "YYYY-MM-DD", timeFormat: false }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - label: Tags
        label_singular: "Tag"
        name: "tags"
        widget: list
        summary: "{{fields.tag}}"
        field:
          label: Tag
          name: tag
          widget: relation
          collection: "meta"
          file: "tags"
          searchFields:
            - "tags.*.name"
          displayFields:
            - "tags.*.name"
          valueField: "tags.*.slug"
      - label: "Body"
        name: "body"
        widget: "markdown"
